 taoquan/Resources/gamescene/41.png
 taoquan/Resources/gamescene/42.png
 taoquan/Resources/gamescene/43.png
 taoquan/Resources/gamescene/44.png
 taoquan/Resources/gamescene/45.png
 taoquan/Resources/gamescene/46.png
 taoquan/Resources/gamescene/47.png
 taoquan/Resources/gamescene/48.png
 taoquan/Resources/gamescene/49.png
 taoquan/Resources/gamescene/Down.png
 taoquan/Resources/gamescene/Up.png
 taoquan/Resources/gamescene/backButton.png
 taoquan/Resources/gamescene/foundation2.png
 taoquan/Resources/gamescene/foundation3.png
 taoquan/Resources/gamescene/foundation4.png
 taoquan/Resources/gamescene/foundationProjection.png
 taoquan/Resources/selectlevel/fileLevelButton1.png
 taoquan/Resources/selectlevel/fileLevelButton2.png
 taoquan/Resources/selectlevel/fileNumber2.png
 taoquan/Resources/selectlevel/gameBG1.png
 taoquan/Resources/selectlevel/gameBG2.png
 taoquan/Resources/selectlevel/gameBG3.png
 taoquan/Resources/selectlevel/gameBG4.png
